server:
  port: 8666
  error:
    include-message: ALWAYS

spring:
  application:
    name: payment
  main:
    allow-bean-definition-overriding: true
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
      profiles:
        active: ${PROFILE}